[app]
  debug = false
  host = "0.0.0.0"
  port = 8088
  token = "b947f276-e761-431f-928d-30ba93a397c1"

[[client.infos]]
  host = "x.x.x.x"
  port = "80"
  token = "b947f276-e761-431f-928d-30ba93a397c1"
[[client.infos]]
  host = "x.x.x.x"
  port = "8087"
  token = "b947f276-e761-431f-928d-30ba93a397c1"

  [app.logger]
    format = "2006/01/02 15:04:05"
    level = "debug"
    name = "application"
